### ISSUE TITLE
Error when trying to download rack-server tech support file

### ISSUE THREAD

**Issue by bingoarunprasath** [CiscoUcs/ucsmsdk#102]
I am trying to invoke the following. 
```
get_ucs_tech_support(handle,file_dir='./',file_name='ucsm-rack.tar', rack_server_id = 1 ,rack_adapter_id='all')
```
But it is failing with the following error
```
Traceback (most recent call last):
  File "testucs.py", line 11, in <module>
    get_ucs_tech_support(handle,file_dir='./',file_name='ucsm-rack.tar', rack_server_id = 1 ,rack_adapter_id='all')
  File "/usr/local/lib/python2.7/dist-packages/ucsmsdk/utils/ucstechsupport.py", line 229, in get_ucs_tech_support
    handle.commit()
  File "/usr/local/lib/python2.7/dist-packages/ucsmsdk/ucshandle.py", line 707, in commit
    response = self.post_elem(elem)
  File "/usr/local/lib/python2.7/dist-packages/ucsmsdk/ucssession.py", line 262, in post_elem
    response = xc.from_xml_str(response_str, self)
  File "/usr/local/lib/python2.7/dist-packages/ucsmsdk/ucsxmlcodec.py", line 88, in from_xml_str
    raise ex.UcsException(error_code, error_descr)
ucsmsdk.ucsexception.UcsException: [ErrorCode]: ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: unknown property value None, name rackServerId, class sysdebugTechSupportCmdOpt [sys/tech-support-files/tech
```
VERSION : 
$ pip list | grep ucs
ucsmsdk (0.9.1.1)

I am able to download UCSM logs, but I am not able to download rack-server logs.

**Comment by vvb** [comment]
@bingoarunprasath thanks for reporting this issue. I see that there is indeed an issue with the code. This will be fixed in about a day.

**Comment by vvb** [comment]
fixed as a part of #105

**Comment by bingoarunprasath** [comment]
Works like a charm :+1:  Thank you

**Comment by vvb** [comment]
thanks for the update. keep finding issues 👍
