### ISSUE TITLE
Unicode is not handled properly in ucsmo.py

### ISSUE THREAD

**Issue by GSoponski** [CiscoUcs/ucsmsdk#123]
Using version 0.9.2.0 of UCSMSDK and python 2.6.6

Code to replicate issue:
```
from ucsmsdk.mometa.compute.ComputeBlade import ComputeBlade
dn = u'sys/chassis-1'
blade_num = '1'
b = ComputeBlade(parent_mo_or_dn=dn, lc='rediscover', descr='', usr_lbl='', admin_power='policy', policy_owner='local', slot_id=blade_num, name='')
```

Traceback:
> Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/ucsmsdk-0.9.2.0-py2.6.egg/ucsmsdk/mometa/compute/ComputeBlade.py", line 1794, in \_\_init\_\_
    ManagedObject.\_\_init\_\_(self, "ComputeBlade", parent_mo_or_dn, **kwargs)
  File "/usr/lib/python2.6/site-packages/ucsmsdk-0.9.2.0-py2.6.egg/ucsmsdk/ucsmo.py", line 73, in \_\_init\_\_
    self._set_parent_mo_or_dn(parent_mo_or_dn)
  File "/usr/lib/python2.6/site-packages/ucsmsdk-0.9.2.0-py2.6.egg/ucsmsdk/ucsmo.py", line 93, in _set_parent_mo_or_dn
    raise ValueError('parent mo or dn must be specified')
ValueError: parent mo or dn must be specified

The problem appears to be line 90 and 471 in ucsmo.py:
`elif isinstance(parent_mo_or_dn, str)`
 Using `basestring` instead of `str` fixes the issue.

**Comment by vvb** [comment]
fix has been committed.
