### ISSUE TITLE
on python3.8 tests fail due to dictionary sorting

### ISSUE THREAD

**Issue by scarabeusiv** [CiscoUcs/ucsmsdk#188]
With python3.8 the dicts are auto sorted and so the result xml params have different order.

The log from the tests:
```
[   42s] ======================================================================
[   42s] FAIL: tests.common.test_ucstoxml.test_001_mo_to_xml
[   42s] ----------------------------------------------------------------------
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
[   42s]     self.test(*self.arg)
[   42s]   File "/home/abuild/rpmbuild/BUILD/ucsmsdk-0.9.8/tests/common/test_ucstoxml.py", line 28, in test_001_mo_to_xml
[   42s]     assert_equal(xml_str, expected)
[   42s] AssertionError: b'<fabricVsan name="test" status="modified" dn="org-root/net-test" />' != b'<fabricVsan dn="org-root/net-test" name="test" status="modified" />'
[   42s] 
[   42s] ======================================================================
[   42s] FAIL: tests.common.test_ucstoxml.test_001_mo_heirarchy_to_xml
[   42s] ----------------------------------------------------------------------
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
[   42s]     self.test(*self.arg)
[   42s]   File "/home/abuild/rpmbuild/BUILD/ucsmsdk-0.9.8/tests/common/test_ucstoxml.py", line 69, in test_001_mo_heirarchy_to_xml
[   42s]     assert_equal(xc.to_xml_str(obj.to_xml()), expected)
[   42s] AssertionError: b'<me[48 chars]ent" id="1" mostRecent="no" rn="1" suspect="no[581 chars]st1>' != b'<me[48 chars]ent" dn="sys/chassis-1/blade-2/board/memarray-[581 chars]st1>'
[   42s] 
[   42s] ======================================================================
[   42s] FAIL: tests.common.test_unknown_props.test_001_knownmo_unknownprop
[   42s] ----------------------------------------------------------------------
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
[   42s]     self.test(*self.arg)
[   42s]   File "/home/abuild/rpmbuild/BUILD/ucsmsdk-0.9.8/tests/common/test_unknown_props.py", line 35, in test_001_knownmo_unknownprop
[   42s]     assert_equal(result_str, expected)
[   42s] AssertionError: b'<lsServer name="ra11" agentPolicyName="" type="inst[49 chars]" />' != b'<lsServer agentPolicyName="" dn="ls-ra11" name="ra1[49 chars]" />'
[   42s] 
[   42s] ======================================================================
[   42s] FAIL: tests.generic_mo.test_ucsgmo.test_002_create_gmo_using_param_dict
[   42s] ----------------------------------------------------------------------
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
[   42s]     self.test(*self.arg)
[   42s]   File "/home/abuild/rpmbuild/BUILD/ucsmsdk-0.9.8/tests/generic_mo/test_ucsgmo.py", line 61, in test_002_create_gmo_using_param_dict
[   42s]     assert_equal(xml_str, expected)
[   42s] AssertionError: b'<te[19 chars]="3" rn="" dn=""><testLsB a="1" b="2" c="3" rn[18 chars]LsA>' != b'<te[19 chars]="3" dn="" rn=""><testLsB a="1" b="2" c="3" dn[18 chars]LsA>'
[   42s] 
[   42s] ======================================================================
[   42s] FAIL: tests.generic_mo.test_ucsgmo.test_003_create_gmo_using_param_dict
[   42s] ----------------------------------------------------------------------
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
[   42s]     self.test(*self.arg)
[   42s]   File "/home/abuild/rpmbuild/BUILD/ucsmsdk-0.9.8/tests/generic_mo/test_ucsgmo.py", line 73, in test_003_create_gmo_using_param_dict
[   42s]     assert_equal(xml_str, expected)
[   42s] AssertionError: b'<te[19 chars]="3" rn="parent" dn="org-root/parent"><testLsB[47 chars]LsA>' != b'<te[19 chars]="3" dn="org-root/parent" rn="parent"><testLsB[47 chars]LsA>'
[   42s] 
[   42s] ======================================================================
[   42s] FAIL: tests.generic_mo.test_ucsgmo.test_004_create_gmo_using_parent_mo
[   42s] ----------------------------------------------------------------------
[   42s] Traceback (most recent call last):
[   42s]   File "/usr/lib/python3.8/site-packages/nose/case.py", line 197, in runTest
[   42s]     self.test(*self.arg)
[   42s]   File "/home/abuild/rpmbuild/BUILD/ucsmsdk-0.9.8/tests/generic_mo/test_ucsgmo.py", line 84, in test_004_create_gmo_using_parent_mo
[   42s]     assert_equal(xml_str, expected)
[   42s] AssertionError: b'<te[19 chars]="3" rn="parent" dn="org-root/parent"><testLsB[47 chars]LsA>' != b'<te[19 chars]="3" dn="org-root/parent" rn="parent"><testLsB[47 chars]LsA>'
[   42s] 
[   42s] ----------------------------------------------------------------------
```

It is quite obvious from the above the content is present just differently sorted compared to the expectation.

**Comment by vvb** [comment]
Thanks for reporting this issue. we will either need to do a element by element compare or just use the xmldiff python lib.
