### ISSUE TITLE
MacOSX cannot start GUI

### ISSUE THREAD

**Issue by vhristev** [CiscoUcs/ucsmsdk#195]
UCS manager version: 3.1(2e) 

My main goal is to update LDAP user which we use to connect to AD 

`LDAP server:
    Hostname, FQDN or IP address   DN to search and read    Port  SSL  Password
          CNw=MY_ACCOUNT,OU=Generic,OU=ServiceAccounts,OU=Corp,OU=Common,DC=MYDOMAIN,DC=com`
 
I'm in the same situation that cannot run GUI from Python2 and python3 tried so many different java versions without success. What do you mean by "collect and download the logs from HTML UI " any procedure how I can do that? 

`~/Downloads/TEMP » python2 ucs.py
2020-04-16 21:10:40,889 - ucs - DEBUG - AuthToken: <01558733253714801873951>
2020-04-16 21:10:40,889 - ucs - DEBUG - UCSM URL: <https://FQDN:443/ucsm/ucsm.jnlp?ucsmToken=01558733253714801873951>
2020-04-16 21:10:40,889 - ucs - DEBUG - javaws path: </usr/bin/javaws>
2020-04-16 21:10:41,728 - ucs - DEBUG - Temp Directory: </var/folders/d6/6w0_g9md4b1cwxp9bmrr39x00000gp/T>
2020-04-16 21:10:41,808 - ucs - DEBUG - Java Version: <14.0.1>
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
`

For me it seems 'temp.jnlp' is not created at all 

`CouldNotLoadArgumentException[ Could not load file/URL specified: /var/folders/d6/6w0_g9md4b1cwxp9bmrr39x00000gp/T/temp.jnlp]
	at com.sun.javaws.Main.launchApp(Unknown Source)
	at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
	at com.sun.javaws.Main.access$000(Unknown Source)
	at com.sun.javaws.Main$1.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.FileNotFoundException: /var/folders/d6/6w0_g9md4b1cwxp9bmrr39x00000gp/T/temp.jnlp (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.sun.javaws.jnl.LaunchDescFactory.buildDescriptor(Unknown Source)
	... 5 more
`
`~/Downloads/TEMP » java -version
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)`

@vbb mentioned something about HTML5 GUI logs  '_collect and download the logs from HTML UI_ ' any idea how to do it is there procedure. 
https://github.com/CiscoUcs/ucsmsdk/issues/159#issuecomment-319616115

**Comment by vhristev** [comment]
I found what @vbb was referring too: 

https://www.cisco.com/c/en/us/td/docs/unified_computing/ucs/sw/msft_tools/powertools/ucs_powertool_book/2x/b_Cisco_UCSM_PowerTool_UG_Release_2x/b_Cisco_UCSM_PowerTool_UG_Release_2x_chapter_010.html#id_16074

Or check that out
https://youtu.be/WlvCiS3l6cM?t=2953 

Now i just need to 

This is how i genereate the code. 
```
from ucsmsdk.utils.converttopython import convert_to_ucs_python
xmlpath = input('Please provide full path of Cisco UCS XML log: ')
convert_to_ucs_python(xml=True, literal_path=xmlpath)

```

```
 » python3 ucs-convert_to_ucs.py
Please provide full path of Cisco UCS XML log: /Users/vhristev/Downloads/LDAPsettings_xmlReq.log
### Please review the generated cmdlets before deployment.

##### Start-Of-PythonScript #####

from ucsmsdk.mometa.aaa.AaaLdapProvider import AaaLdapProvider

mo = AaaLdapProvider(parent_mo_or_dn="sys/ldap-ext", key="MY_SECRET_PASS", name="WDC-AD-VIP.mydomain.com")
handle.add_mo(mo, True)

handle.commit()
##### End-Of-PythonScript #####
### End of Convert-To-Python ###
```

The problem is I have a lot of UCS's chassis and as you can see script generates LDAP Provider name to identify it ( 'name' ) . I was able to get the LDAP  class and now the only thing i need to do is to replace the 'name' in the script with ' ldaps[0]'. name key  ( check below ) 
```
ldaps = handle.query_classid('aaaLdapProvider')
print(vars(ldaps[0]))
```
